version: '3.3'
services:
  bookstore:
    container_name: bookstore
    build:
        context: ./bookstore
        dockerfile: Dockerfile
    image: 'joko/bookstore'
    ports:
      - '8090:8090'
    depends_on:
      - configuration-server
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"

  reading:
    container_name: reading
    image: 'joko/reading'
    build:
        context: ./reading
        dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
            - configuration-server
    links:
      - configuration-server:configuration-server
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"

  configuration-server:
    container_name: configuration-server
    image: 'joko/configuration-server'
    build:
        context: ./configuration-service
        dockerfile: Dockerfile
    ports:
      - '8888:8888'
    networks:
      - micro

networks:
  micro:
    driver: bridge

