version: '3.3'
services:
  bookstore:
    container_name: bookstore
    build:
        context: ./bookstore
        dockerfile: Dockerfile
    image: 'joko/bookstore'
    ports:
      - '8090:8090'
    links:
      - eureka-server:eureka-server
      - configuration-server:configuration-server
      - zipkin-server:zipkin-server
    depends_on:
      - configuration-server
      - eureka-server
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=configuration-server:8888,eureka-server:8761"

  reading:
    container_name: reading
    image: 'joko/reading'
    build:
        context: ./reading
        dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
            - configuration-server
            - eureka-server
    links:
      - eureka-server:eureka-server
      - configuration-server:configuration-server
      - bookstore:bookstore
      - zipkin-server:zipkin-server
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=configuration-server:8888,eureka-server:8761,zipkin-server:9411"

  configuration-server:
    container_name: configuration-server
    image: 'joko/configuration-server'
    build:
        context: ./configuration-service
        dockerfile: Dockerfile
    ports:
      - '8888:8888'
    links:
      - eureka-server:eureka-server
    networks:
      - micro

  eureka-server:
    container_name: eureka-server
    build:
        context: ./eureka-server
        dockerfile: Dockerfile
    image: 'joko/eureka-server'
    ports:
      - '8761:8761'
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
  
  zuul-api-gateway:
    container_name: zuul-api-gateway
    build:
        context: ./zuul-api-gateway
        dockerfile: Dockerfile
    image: 'joko/zuul-api-gateway'
    links:
      - eureka-server:eureka-server
      - configuration-server:configuration-server
      - bookstore:bookstore
      - reading:reading
      - zipkin-server:zipkin-server
    ports:
      - '8181:8181'
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=configuration-server:8888,eureka-server:8761"

  reading2:
    container_name: reading2
    image: 'joko/reading'
    depends_on:
            - configuration-server
            - eureka-server
    links:
      - eureka-server:eureka-server
      - configuration-server:configuration-server
      - bookstore:bookstore
      - zipkin-server:zipkin-server
    networks:
      - micro
    environment:
            - "spring.cloud.config.uri=http://configuration-server:8888/"
            - "SPRING_PROFILES_ACTIVE=dev"
            - "WAIT_HOSTS=configuration-server:8888,eureka-server:8761"

  zipkin-server:
        container_name: 'zipkin'
        image: 'openzipkin/zipkin'
        ports:
             - '9411:9411'
        networks:
             - micro

networks:
  micro:
    driver: bridge


